name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check code format
      run: |
        npm run build
        npx prettier --check "lib/**/*.ts" "test/**/*.ts"
        npx eslint "lib/**/*.ts" "test/**/*.ts"

    - name: Run tests with coverage
      run: npm run test:coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

    - name: Cache test results
      uses: actions/cache@v3
      with:
        path: |
          coverage
          .jest-cache
        key: ${{ runner.os }}-test-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-test-

  synth:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Synthesize CloudFormation templates
      run: npm run synth

    - name: Archive CloudFormation templates
      uses: actions/upload-artifact@v3
      with:
        name: cloudformation-templates
        path: cdk.out/*.template.json
        retention-days: 5